# remote_theme: pmarsceill/just-the-docs

# # Heading anchor links appear on hover over h1-h6 tags in page content
# # allowing users to deep link to a particular heading on a page.
# #
# # Supports true (default) or false
# heading_anchors: true

# # Back to top link
# back_to_top: true
# back_to_top_text: "Back to top"

# permalink: pretty
# exclude: ["docs","news"]



# # Footer last edited timestamp
# last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# collections:
#   docs:
#     permalink: "docs"
#     output: true
#   news:
#     permalink: "news"
#     output: true
# just_the_docs:
#   collections:
#     docs:
#       name: Documentation
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       nav_exclude: false
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       search_exclude: false
#     news:
#       name: News
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       nav_exclude: false
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       search_exclude: false

title: EMHUB
description: Resource Hub for HKPolyU EM Lab
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
